alias c="clear"
alias v="nvim"
alias resh="source ~/.$(ps -p $$ -o 'comm=')rc"
local LSARGS="--color=always --group-directories-first"
alias ls="ls $LSARGS"
alias la="ls -lAh --color=always"
alias ll="ls -lh --color=always"
alias grep="grep --color=always"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
